port: 7890
socks-port: 7891
mixed-port: 7892
allow-lan: false
bind-address: '*'
mode: rule
log-level: info
ipv6: false

find-process-mode: strict
external-controller: ''
external-controller-cors:
  allow-origins:
    - '*'
  allow-private-network: true
secret: set-your-secret

profile:
  store-selected: true
  store-fake-ip: true

unified-delay: true
tcp-concurrent: true
geodata-mode: false
geodata-loader: standard
geo-auto-update: true
geo-update-interval: 24
geox-url:
  geoip: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat
  geosite: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.metadb
  asn: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb



# # TUN
# tun:
#   enable: false
#   stack: mixed
#   auto-route: true
#   strict-route: false
#   auto-detect-interface: true
#   dns-hijack:
#   - any:53


# DNS
dns:
  enable: true
  prefer-h3: false
  listen: :53
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - '*.lan'
  - '*.local'
  - '*.arpa'
  - time.*.com
  - ntp.*.com
  - time.*.com
  - +.market.xiaomi.com
  - localhost.ptlogin2.qq.com
  - '*.msftncsi.com'
  - www.msftconnecttest.com
  fake-ip-filter-mode: blacklist
  use-hosts: true
  use-system-hosts: false
  respect-rules: false
  default-nameserver:
  - 120.53.53.53
  - 119.29.29.29
  - 1.1.1.1
  nameserver-policy:
    'geosite:cn,private':
      - https://120.53.53.53/dns-query
      - https://119.29.29.29/dns-query
    'geosite:geolocation-!cn':
      - https://1.1.1.1/dns-query
      - https://8.8.8.8/dns-query
  proxy-server-nameserver:
    - https://1.1.1.1/dns-query
    - https://8.8.8.8/dns-query
  direct-nameserver:
    - https://119.29.29.29/dns-query
    - https://120.53.53.53/dns-query
    - https://223.5.5.5/dns-query
  nameserver:
    - https://120.53.53.53/dns-query
    - https://1.1.1.1/dns-query
  fallback:
  - https://1.1.1.1/dns-query
  - https://dns.google/dns-query
  - https://dns.nextdns.io/dns-query
  - https://dns.quad9.net/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - gfw
    ipcidr:
      - 240.0.0.0/4
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'



# sniffer
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true

# NTP
ntp:
  enable: true
  write-to-system: false
  server: ntp.aliyun.com
  port: 123
  interval: 30